# Site settings
title: Ann Marie Doyle
email: am@amdoyle.com
description: Web Developer, Creater, Coffee Lover, Book Nerd, & Sometimes Adventure
baseurl: ""
url: "http://www.amdoyle.com/"
twitter_username: AmDoyle
github_username:  amdoyle

# Build settings
markdown: kramdown
