# Site settings
title: Ann Marie Doyle
email: am@amdoyle.com
description: Web Developer, Creater, Coffee Lover & Sometimes Adventurer
baseurl: "http://amdoyle.github.io/amdoyle/"
url: "http://amdoyle.github.io/amdoyle/"
twitter_username: AmDoyle
github_username:  amdoyle
linkedin_username: annmariedoyle

# Build settings
markdown: kramdown

include:
- _scripts
